package cmd.novo.painel;

import cmd.Validacao.Validar;
import java.awt.Color;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PnlJuridica extends javax.swing.JPanel {

    public String getTxt_cnpj_pnl() {//Fornece acesso a outras classes
        return txt_cnpj_pnl.getText();
    }
    public String getTxt_razaoSocial_pnl() {//Fornece acesso a outras classes
        return txt_razaoSocial_pnl.getText();
    }
    public String getTxt_nomeReferencia_pnl() {//Fornece acesso a outras classes
        return txt_nomeReferencia_pnl.getText();
    }
    public String getTxt_ramoAtuacao_pnl() {//Fornece acesso a outras classes
        return txt_ramoAtuacao_pnl.getText();
    }
    public Date getTxt_datafundacao_pnl() {//Fornece acesso a outras classes
        return txt_datafundacao_pnl.getDate();
    }
    
    public void setTxt_cnpj_pnl(String cnpj) {//Fornece acesso a outras classes
        this.txt_cnpj_pnl.setText(cnpj);
    }
    public void setTxt_razaoSocial_pnl(String razao) {//Fornece acesso a outras classes
        this.txt_razaoSocial_pnl.setText(razao);
    }
    public void setTxt_nomeReferencia_pnl(String nome) {//Fornece acesso a outras classes
        this.txt_nomeReferencia_pnl.setText(nome);
    }
    public void setTxt_ramoAtuacao_pnl(String ramo) {//Fornece acesso a outras classes
        this.txt_ramoAtuacao_pnl.setText(ramo);
    }
    public void setTxt_datafundacao_pnl(Date dat) {//Fornece acesso a outras classes
        this.txt_datafundacao_pnl.setDate(dat);
    }
    
    public void setEnabled_cnpj_pnl(boolean val) {
        txt_cnpj_pnl.setEnabled(val);
    }

    /**
     * Creates new form pnl_empresa
     */
    public PnlJuridica() {
        initComponents();
        pnl_empresa.setBackground(Color.WHITE);
        txt_datafundacao_pnl.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_empresa = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_razaoSocial_pnl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_ramoAtuacao_pnl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cnpj_pnl = new javax.swing.JFormattedTextField();
        txt_datafundacao_pnl = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txt_nomeReferencia_pnl = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CNPJ:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Razão social:*");

        txt_razaoSocial_pnl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Ramo de atuação:");

        txt_ramoAtuacao_pnl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Data de fundação:");

        try {
            txt_cnpj_pnl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cnpj_pnl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cnpj_pnlFocusLost(evt);
            }
        });

        txt_datafundacao_pnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nome p/ contato:*");

        txt_nomeReferencia_pnl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nomeReferencia_pnl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nomeReferencia_pnlFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnl_empresaLayout = new javax.swing.GroupLayout(pnl_empresa);
        pnl_empresa.setLayout(pnl_empresaLayout);
        pnl_empresaLayout.setHorizontalGroup(
            pnl_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_datafundacao_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_razaoSocial_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ramoAtuacao_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txt_cnpj_pnl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_empresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nomeReferencia_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl_empresaLayout.setVerticalGroup(
            pnl_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cnpj_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_razaoSocial_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomeReferencia_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ramoAtuacao_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_datafundacao_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cnpj_pnlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cnpj_pnlFocusLost
//        Validar vali = new Validar();
//        if (vali.validarCnpj(txt_cnpj_pnl.getText()) == false) {
//            JOptionPane.showMessageDialog(null, "Verificar o CNPJ");
//        }
    }//GEN-LAST:event_txt_cnpj_pnlFocusLost

    private void txt_nomeReferencia_pnlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeReferencia_pnlFocusLost
              Validar vali = new Validar();
        if (vali.validarVazio(txt_nomeReferencia_pnl.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Verificar o nome para contato");
        }
    }//GEN-LAST:event_txt_nomeReferencia_pnlFocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnl_empresa;
    private javax.swing.JFormattedTextField txt_cnpj_pnl;
    private com.toedter.calendar.JDateChooser txt_datafundacao_pnl;
    private javax.swing.JTextField txt_nomeReferencia_pnl;
    private javax.swing.JTextField txt_ramoAtuacao_pnl;
    private javax.swing.JTextField txt_razaoSocial_pnl;
    // End of variables declaration//GEN-END:variables
    
    //CNPJ válido: 31.061.861/0001-03
}
