/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmd.novo.telas;

import cmd.novo.GerenteDeJanelas;
import static cmd.novo.telas.TPrincipal.jDesktopPane1;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class TCalculo extends javax.swing.JInternalFrame {
    
    GerenteDeJanelas gerenteDeJanelas;
    public static TCalculo calculoT;

    public static TCalculo getInstancia() {
        if (calculoT == null) {
            calculoT = new TCalculo();
        }
        return calculoT;
    }

    /**
     * Creates new form NewJFrame
     */
    public TCalculo() {
        this.gerenteDeJanelas = new GerenteDeJanelas(jDesktopPane1);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        pnl_alturaLargura.setBackground(Color.WHITE);
        pnl_ambiente.setBackground(Color.WHITE);
        pnl_botoes.setBackground(Color.WHITE);
        pnl_valor.setBackground(Color.WHITE);
        pnl_janela.setBackground(Color.WHITE);
        pnl_porta.setBackground(Color.WHITE);
        pnl_maoObra.setBackground(Color.WHITE);
        pnl_janela.setVisible(false);
        pnl_porta.setVisible(false);
        pnl_maoObra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGrup_portas = new javax.swing.ButtonGroup();
        rdGrup_janelas = new javax.swing.ButtonGroup();
        rdGrup_maoDeObra = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_construcoes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_materiais = new javax.swing.JTable();
        pnl_botoes = new javax.swing.JPanel();
        btn_calcular = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_alterar1 = new javax.swing.JButton();
        pnl_janela = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rd_JanelaSim = new javax.swing.JRadioButton();
        rd_JanelaNao = new javax.swing.JRadioButton();
        lb_qtdJanelas = new javax.swing.JLabel();
        cmb_qtdJanelas = new javax.swing.JComboBox();
        pnl_porta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rd_PortaSim = new javax.swing.JRadioButton();
        rd_PortaNao = new javax.swing.JRadioButton();
        lb_qtdPortas = new javax.swing.JLabel();
        cmb_qtdPortas = new javax.swing.JComboBox();
        pnl_valor = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnl_maoObra = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rd_ObraSim = new javax.swing.JRadioButton();
        rd_ObraNao = new javax.swing.JRadioButton();
        pnl_ambiente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        pnl_alturaLargura = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_largura = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cálculo de Drywall");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bem-Vindo à área de Cáculo de Drywall");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Escolha a Construção:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Escolha o material:");

        tb_construcoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_construcoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód. constr.", "Tipo constr.", "Descrição", "Qualidade"
            }
        ));
        jScrollPane1.setViewportView(tb_construcoes);

        tb_materiais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_materiais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cód material", "Tipo", "Descrição", "Const. metro", "Preço unit.", "Qtde. min."
            }
        ));
        jScrollPane2.setViewportView(tb_materiais);

        btn_calcular.setBackground(new java.awt.Color(153, 153, 255));
        btn_calcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calcular.setText("Calcular Parede");

        btn_alterar.setBackground(new java.awt.Color(153, 153, 255));
        btn_alterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_alterar.setText("Alterar Dados");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_deletar.setBackground(new java.awt.Color(153, 153, 255));
        btn_deletar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_deletar.setText("Deletar Dados");

        btn_sair.setBackground(new java.awt.Color(153, 153, 255));
        btn_sair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_alterar1.setBackground(new java.awt.Color(153, 153, 255));
        btn_alterar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_alterar1.setText("Salvar Dados");
        btn_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_botoesLayout = new javax.swing.GroupLayout(pnl_botoes);
        pnl_botoes.setLayout(pnl_botoesLayout);
        pnl_botoesLayout.setHorizontalGroup(
            pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_botoesLayout.createSequentialGroup()
                        .addGroup(pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_deletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_alterar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_botoesLayout.setVerticalGroup(
            pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn_alterar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deletar)
                .addGap(26, 26, 26)
                .addComponent(btn_sair)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Janelas?");

        rdGrup_janelas.add(rd_JanelaSim);
        rd_JanelaSim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd_JanelaSim.setText("Sim");
        rd_JanelaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_JanelaSimActionPerformed(evt);
            }
        });

        rdGrup_janelas.add(rd_JanelaNao);
        rd_JanelaNao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd_JanelaNao.setSelected(true);
        rd_JanelaNao.setText("Não");
        rd_JanelaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_JanelaNaoActionPerformed(evt);
            }
        });

        lb_qtdJanelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_qtdJanelas.setText("Quantidade:");
        lb_qtdJanelas.setEnabled(false);

        cmb_qtdJanelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_qtdJanelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmb_qtdJanelas.setEnabled(false);

        javax.swing.GroupLayout pnl_janelaLayout = new javax.swing.GroupLayout(pnl_janela);
        pnl_janela.setLayout(pnl_janelaLayout);
        pnl_janelaLayout.setHorizontalGroup(
            pnl_janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_janelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(rd_JanelaNao)
                    .addComponent(rd_JanelaSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnl_janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_qtdJanelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_qtdJanelas))
                .addContainerGap())
        );
        pnl_janelaLayout.setVerticalGroup(
            pnl_janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_janelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_qtdJanelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_qtdJanelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_janelaLayout.createSequentialGroup()
                        .addComponent(rd_JanelaSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd_JanelaNao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Portas?");

        rdGrup_portas.add(rd_PortaSim);
        rd_PortaSim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd_PortaSim.setText("Sim");
        rd_PortaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_PortaSimActionPerformed(evt);
            }
        });

        rdGrup_portas.add(rd_PortaNao);
        rd_PortaNao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd_PortaNao.setSelected(true);
        rd_PortaNao.setText("Não");
        rd_PortaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_PortaNaoActionPerformed(evt);
            }
        });

        lb_qtdPortas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_qtdPortas.setText("Quantidade:");
        lb_qtdPortas.setEnabled(false);

        cmb_qtdPortas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_qtdPortas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmb_qtdPortas.setEnabled(false);

        javax.swing.GroupLayout pnl_portaLayout = new javax.swing.GroupLayout(pnl_porta);
        pnl_porta.setLayout(pnl_portaLayout);
        pnl_portaLayout.setHorizontalGroup(
            pnl_portaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_portaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_portaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(rd_PortaNao)
                    .addComponent(rd_PortaSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnl_portaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_qtdPortas)
                    .addComponent(cmb_qtdPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl_portaLayout.setVerticalGroup(
            pnl_portaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_portaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_portaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_qtdPortas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_portaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_portaLayout.createSequentialGroup()
                        .addComponent(rd_PortaSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd_PortaNao))
                    .addComponent(cmb_qtdPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Valor total da tipologia: ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("#####");

        javax.swing.GroupLayout pnl_valorLayout = new javax.swing.GroupLayout(pnl_valor);
        pnl_valor.setLayout(pnl_valorLayout);
        pnl_valorLayout.setHorizontalGroup(
            pnl_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_valorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_valorLayout.setVerticalGroup(
            pnl_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_valorLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnl_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mão de Obra:");

        rdGrup_maoDeObra.add(rd_ObraSim);
        rd_ObraSim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd_ObraSim.setText("Sim");

        rdGrup_maoDeObra.add(rd_ObraNao);
        rd_ObraNao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd_ObraNao.setSelected(true);
        rd_ObraNao.setText("Não");

        javax.swing.GroupLayout pnl_maoObraLayout = new javax.swing.GroupLayout(pnl_maoObra);
        pnl_maoObra.setLayout(pnl_maoObraLayout);
        pnl_maoObraLayout.setHorizontalGroup(
            pnl_maoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_maoObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_maoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(rd_ObraSim)
                    .addComponent(rd_ObraNao))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pnl_maoObraLayout.setVerticalGroup(
            pnl_maoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_maoObraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_ObraSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_ObraNao))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cond. de ambiente:");

        jLabel30.setBackground(new java.awt.Color(255, 0, 0));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(54, 54, 54));
        jLabel30.setText("(obrigatório)");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.setName(""); // NOI18N

        jCheckBox1.setText("Seco (ST)");

        jCheckBox2.setText("Resistência a fogo (RF)");

        jCheckBox3.setText("Resistência a umidade (RU)");

        javax.swing.GroupLayout pnl_ambienteLayout = new javax.swing.GroupLayout(pnl_ambiente);
        pnl_ambiente.setLayout(pnl_ambienteLayout);
        pnl_ambienteLayout.setHorizontalGroup(
            pnl_ambienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ambienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ambienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ambienteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ambienteLayout.setVerticalGroup(
            pnl_ambienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ambienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ambienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Altura da parede:");

        txt_altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#"))));
        txt_altura.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("m");

        txt_largura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#"))));
        txt_largura.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("m");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Largura da parede:");

        jLabel25.setBackground(new java.awt.Color(255, 0, 0));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(54, 54, 54));
        jLabel25.setText("(obrigatório)");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.setName(""); // NOI18N

        jLabel26.setBackground(new java.awt.Color(255, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 54, 54));
        jLabel26.setText("(obrigatório)");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.setName(""); // NOI18N

        javax.swing.GroupLayout pnl_alturaLarguraLayout = new javax.swing.GroupLayout(pnl_alturaLargura);
        pnl_alturaLargura.setLayout(pnl_alturaLarguraLayout);
        pnl_alturaLarguraLayout.setHorizontalGroup(
            pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_alturaLarguraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_alturaLarguraLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_alturaLarguraLayout.createSequentialGroup()
                        .addGroup(pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_alturaLarguraLayout.createSequentialGroup()
                                .addComponent(txt_largura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(pnl_alturaLarguraLayout.createSequentialGroup()
                                .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(pnl_alturaLarguraLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_alturaLarguraLayout.setVerticalGroup(
            pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_alturaLarguraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_alturaLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_largura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel27.setBackground(new java.awt.Color(255, 0, 0));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(54, 54, 54));
        jLabel27.setText("(obrigatório)");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnl_janela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnl_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnl_maoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnl_alturaLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnl_ambiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addComponent(pnl_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(pnl_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_ambiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_alturaLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnl_janela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_porta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnl_maoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel27)
                            .addComponent(jLabel11)))
                    .addComponent(pnl_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd_PortaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_PortaNaoActionPerformed
        lb_qtdPortas.setEnabled(false);
        cmb_qtdPortas.setEnabled(false);
    }//GEN-LAST:event_rd_PortaNaoActionPerformed

    private void rd_JanelaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_JanelaSimActionPerformed
        cmb_qtdJanelas.setEnabled(true);
        lb_qtdJanelas.setEnabled(true);
    }//GEN-LAST:event_rd_JanelaSimActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void rd_PortaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_PortaSimActionPerformed
        lb_qtdPortas.setEnabled(true);
        cmb_qtdPortas.setEnabled(true);
    }//GEN-LAST:event_rd_PortaSimActionPerformed

    private void rd_JanelaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_JanelaNaoActionPerformed
        cmb_qtdJanelas.setEnabled(false);
        lb_qtdJanelas.setEnabled(false);
    }//GEN-LAST:event_rd_JanelaNaoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_alterar1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_alterar1;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JComboBox cmb_qtdJanelas;
    private javax.swing.JComboBox cmb_qtdPortas;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_qtdJanelas;
    private javax.swing.JLabel lb_qtdPortas;
    private javax.swing.JPanel pnl_alturaLargura;
    private javax.swing.JPanel pnl_ambiente;
    private javax.swing.JPanel pnl_botoes;
    private javax.swing.JPanel pnl_janela;
    private javax.swing.JPanel pnl_maoObra;
    private javax.swing.JPanel pnl_porta;
    private javax.swing.JPanel pnl_valor;
    private javax.swing.ButtonGroup rdGrup_janelas;
    private javax.swing.ButtonGroup rdGrup_maoDeObra;
    private javax.swing.ButtonGroup rdGrup_portas;
    private javax.swing.JRadioButton rd_JanelaNao;
    private javax.swing.JRadioButton rd_JanelaSim;
    private javax.swing.JRadioButton rd_ObraNao;
    private javax.swing.JRadioButton rd_ObraSim;
    private javax.swing.JRadioButton rd_PortaNao;
    private javax.swing.JRadioButton rd_PortaSim;
    private javax.swing.JTable tb_construcoes;
    private javax.swing.JTable tb_materiais;
    private javax.swing.JFormattedTextField txt_altura;
    private javax.swing.JFormattedTextField txt_largura;
    // End of variables declaration//GEN-END:variables
}
