/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmd.novo.telas;

import cmd.novo.GerenteDeJanelas;
import java.awt.Color;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario Tela principal
 */
public class TPrincipal extends javax.swing.JFrame {

    TCarregamento tCar = new TCarregamento(null, true);

    GerenteDeJanelas gerenteDeJanelas;

    /**
     * Creates new form PrincipalT
     */
    public TPrincipal(String nomeL) {
        initComponents();
        //getContentPane().setBackground(Color.WHITE);
        pnl_botoes.setBackground(new Color(153, 153, 255));

        this.gerenteDeJanelas = new GerenteDeJanelas(jDesktopPane1);

        if (nomeL != null) {
            lb_logado.setText(nomeL);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_botoes = new javax.swing.JPanel();
        btn_cadMateriais = new javax.swing.JButton();
        btn_cadClientes = new javax.swing.JButton();
        btn_calOrcamentoPrj = new javax.swing.JButton();
        btn_relatorios = new javax.swing.JButton();
        btn_cadFuncionarios = new javax.swing.JButton();
        btn_solicitacaoOrcamento = new javax.swing.JButton();
        btn_cadConstrucao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_logado = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/cmd/imagens/logo.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0,0,getWidth(),getHeight(),this);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        btn_cadMateriais.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadMateriais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cadMateriais.setText("Registro de Materiais");
        btn_cadMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadMateriaisActionPerformed(evt);
            }
        });

        btn_cadClientes.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cadClientes.setText("Registro de Clientes");
        btn_cadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadClientesActionPerformed(evt);
            }
        });

        btn_calOrcamentoPrj.setBackground(new java.awt.Color(255, 255, 255));
        btn_calOrcamentoPrj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_calOrcamentoPrj.setText("Orçamento do Projeto");
        btn_calOrcamentoPrj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calOrcamentoPrjActionPerformed(evt);
            }
        });

        btn_relatorios.setBackground(new java.awt.Color(255, 255, 255));
        btn_relatorios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_relatorios.setText("Relatórios");
        btn_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relatoriosActionPerformed(evt);
            }
        });

        btn_cadFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cadFuncionarios.setText("Cadastrar Funcionários");
        btn_cadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadFuncionariosActionPerformed(evt);
            }
        });

        btn_solicitacaoOrcamento.setBackground(new java.awt.Color(255, 255, 255));
        btn_solicitacaoOrcamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_solicitacaoOrcamento.setText("Solicitações de Orçamento");
        btn_solicitacaoOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitacaoOrcamentoActionPerformed(evt);
            }
        });

        btn_cadConstrucao.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadConstrucao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cadConstrucao.setText("Registro de Construção");
        btn_cadConstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadConstrucaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Logado como:");

        lb_logado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_logado.setText("NULL");

        javax.swing.GroupLayout pnl_botoesLayout = new javax.swing.GroupLayout(pnl_botoes);
        pnl_botoes.setLayout(pnl_botoesLayout);
        pnl_botoesLayout.setHorizontalGroup(
            pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cadMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calOrcamentoPrj, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_solicitacaoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_botoesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_logado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnl_botoesLayout.setVerticalGroup(
            pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_botoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_logado))
                .addGap(28, 28, 28)
                .addComponent(btn_cadConstrucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadMateriais)
                .addGap(51, 51, 51)
                .addComponent(btn_cadClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calOrcamentoPrj)
                .addGap(123, 123, 123)
                .addComponent(btn_relatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_solicitacaoOrcamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadFuncionarios)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadFuncionariosActionPerformed
//       TFuncionario fT = new TFuncionario();
//        jDesktopPane1.add(fT);
//        fT.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TFuncionario.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TFuncionario.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try
                }

                janelaCarregamentoFecha();
            }
        };

        t.start();
        janelaCarregamentoAbre();
    }//GEN-LAST:event_btn_cadFuncionariosActionPerformed

    private void btn_solicitacaoOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitacaoOrcamentoActionPerformed
        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TSolicaoOrcamento.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TSolicaoOrcamento.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try

                }

                janelaCarregamentoFecha();
            }
        };

        t.start();
        janelaCarregamentoAbre();
    }//GEN-LAST:event_btn_solicitacaoOrcamentoActionPerformed

    private void btn_cadMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadMateriaisActionPerformed
        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TMaterial.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TMaterial.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try

                }
                janelaCarregamentoFecha();
            }
        };

        t.start();
        janelaCarregamentoAbre();

    }//GEN-LAST:event_btn_cadMateriaisActionPerformed

    private void btn_calOrcamentoPrjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calOrcamentoPrjActionPerformed
        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TOrcamento.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TOrcamento.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try

                }

                janelaCarregamentoFecha();
                
            }
        };

        t.start();
        janelaCarregamentoAbre();
        //t.isAlive();
    }//GEN-LAST:event_btn_calOrcamentoPrjActionPerformed

    private void btn_cadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadClientesActionPerformed
        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TCliente.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TCliente.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try

                }

                janelaCarregamentoFecha();
            }
        };

        t.start();
        janelaCarregamentoAbre();
    }//GEN-LAST:event_btn_cadClientesActionPerformed

    private void btn_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relatoriosActionPerformed
        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TRelatorio.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TRelatorio.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try

                }

                janelaCarregamentoFecha();
            }
        };

        t.start();
        janelaCarregamentoAbre();
    }//GEN-LAST:event_btn_relatoriosActionPerformed

    private void btn_cadConstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadConstrucaoActionPerformed

        Thread t = new Thread() {
            @Override
            public void run() {

                try {
                    gerenteDeJanelas.abrirJanelas(TConstrucao.getInstancia());
                } catch (IllegalArgumentException e) {
                    gerenteDeJanelas.abrirJanelas(TConstrucao.getInstancia());
                    //System.err.println(e);//ERRO ! - Erro - contornado.... retirar todo o try

                }

                janelaCarregamentoFecha();
            }
        };

        t.start();
        janelaCarregamentoAbre();
    }//GEN-LAST:event_btn_cadConstrucaoActionPerformed
    private void janelaCarregamentoAbre() {

        tCar.setVisible(true);
    }

    private void janelaCarregamentoFecha() {

        tCar.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal(null).setVisible(true);
                //new TPrincipal().setVisible(true);//Original, foi alterado quando tentei passar info fo Form Login Para este
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadClientes;
    private javax.swing.JButton btn_cadConstrucao;
    private javax.swing.JButton btn_cadFuncionarios;
    private javax.swing.JButton btn_cadMateriais;
    private javax.swing.JButton btn_calOrcamentoPrj;
    private javax.swing.JButton btn_relatorios;
    private javax.swing.JButton btn_solicitacaoOrcamento;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_logado;
    private javax.swing.JPanel pnl_botoes;
    // End of variables declaration//GEN-END:variables
}
