/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmd.novo.telas;

import cmd.DAO.PedidosDAO;
import java.awt.Color;
import cmd.email.SwingEmailSender;
import cmd.entidade.Pedidos;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */

public class TSolicaoOrcamento extends javax.swing.JInternalFrame {

    //Controla a quantidade de Janelas abertas

    public static TSolicaoOrcamento solicaoOrcamento;

    public static TSolicaoOrcamento getInstancia() {
        if (solicaoOrcamento == null) {
            solicaoOrcamento = new TSolicaoOrcamento();
        }
        return solicaoOrcamento;
    }

    /**
     * Creates new form SolicaoOrcamento
     */
    public TSolicaoOrcamento() 
    {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        pn_conteudo.setBackground(Color.WHITE);
        DefaultTableModel modelo = (DefaultTableModel) tb_orcamento.getModel();
        tb_orcamento.setRowSorter(new TableRowSorter(modelo));
        ReadTable();
       
    }
    public void ReadTable()
    {
        DefaultTableModel modelo = (DefaultTableModel) tb_orcamento.getModel();
        PedidosDAO p = new PedidosDAO();
        modelo.setNumRows(0);
        
        for(Pedidos pe : p.Read())
        {
             modelo.addRow(new Object[]{
               pe.getId(),
               pe.getAltura(),
               pe.getLargura(),
               pe.getQtd_paredes(),
               pe.getEmail(),
               pe.getValor(),
               pe.getAmbiente(),
               pe.getPossui_porta(),
               pe.getPossui_janela(),
               pe.getQtd_porta(),
               pe.getQtd_janela(),
               pe.getAltura_porta(),
               pe.getLargura_porta(),
               pe.getAltura_janela(),
               pe.getLargura_janela(),
               pe.getMao_obra()
           });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_enviarEmail = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pn_conteudo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_orcamento = new javax.swing.JTable();

        setClosable(true);
        setTitle("Solicitação de Orçamentos");

        btn_enviarEmail.setBackground(new java.awt.Color(153, 153, 255));
        btn_enviarEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_enviarEmail.setText("Enviar email ao cliente");
        btn_enviarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarEmailActionPerformed(evt);
            }
        });

        tb_orcamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_orcamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Altura", "Largura", "Quantidade de Paredes", "Email", "Valor disponivel/desejado", "Ambiente", "Quantidade de Portas (Se houver)", "Quantidade Janelas (Se houver)", "Possui Portas", "Altura da Porta", "Largura da Porta", "Possui Janelas", "Altura da Janela", "Largura da Janela", "Mao de Obra"
            }
        ));
        tb_orcamento.setPreferredSize(new java.awt.Dimension(1250, 48));
        jScrollPane1.setViewportView(tb_orcamento);

        javax.swing.GroupLayout pn_conteudoLayout = new javax.swing.GroupLayout(pn_conteudo);
        pn_conteudo.setLayout(pn_conteudoLayout);
        pn_conteudoLayout.setHorizontalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1885, Short.MAX_VALUE)
        );
        pn_conteudoLayout.setVerticalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(pn_conteudo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_enviarEmail)
                        .addGap(0, 787, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enviarEmail)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarEmailActionPerformed
        SwingEmailSender email = new SwingEmailSender();
        email.show();
    }//GEN-LAST:event_btn_enviarEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviarEmail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_conteudo;
    private javax.swing.JTable tb_orcamento;
    // End of variables declaration//GEN-END:variables
}
