package cmd.entidade;
// Generated 29/10/2017 11:08:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private Endereco endereco;
     private Date dataInscricao;
     private Boolean xdead;
     private PessoaFisica pessoaFisica;
     private Set telefones = new HashSet(0);
     private PessoaJuridica pessoaJuridica;
     private Set orcamentos = new HashSet(0);

    public Cliente() {
    }

    public Cliente(Endereco endereco, Date dataInscricao, Boolean xdead, PessoaFisica pessoaFisica, Set telefones, PessoaJuridica pessoaJuridica, Set orcamentos) {
       this.endereco = endereco;
       this.dataInscricao = dataInscricao;
       this.xdead = xdead;
       this.pessoaFisica = pessoaFisica;
       this.telefones = telefones;
       this.pessoaJuridica = pessoaJuridica;
       this.orcamentos = orcamentos;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Date getDataInscricao() {
        return this.dataInscricao;
    }
    
    public void setDataInscricao(Date dataInscricao) {
        this.dataInscricao = dataInscricao;
    }
    public Boolean getXdead() {
        return this.xdead;
    }
    
    public void setXdead(Boolean xdead) {
        this.xdead = xdead;
    }
    public PessoaFisica getPessoaFisica() {
        return this.pessoaFisica;
    }
    
    public void setPessoaFisica(PessoaFisica pessoaFisica) {
        this.pessoaFisica = pessoaFisica;
    }
    public Set getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Set telefones) {
        this.telefones = telefones;
    }
    public PessoaJuridica getPessoaJuridica() {
        return this.pessoaJuridica;
    }
    
    public void setPessoaJuridica(PessoaJuridica pessoaJuridica) {
        this.pessoaJuridica = pessoaJuridica;
    }
    public Set getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Set orcamentos) {
        this.orcamentos = orcamentos;
    }




}


