package cmd.entidade;
// Generated 29/10/2017 11:08:24 by Hibernate Tools 4.3.1



/**
 * Forro generated by hbm2java
 */
public class Forro  implements java.io.Serializable {


     private int codConstrucao;
     private Construcao construcao;
     private Boolean ehSt;
     private Boolean ehRu;
     private Boolean ehRf;
     private Boolean xdead;

    public Forro() {
    }

	
    public Forro(Construcao construcao) {
        this.construcao = construcao;
    }
    public Forro(Construcao construcao, Boolean ehSt, Boolean ehRu, Boolean ehRf, Boolean xdead) {
       this.construcao = construcao;
       this.ehSt = ehSt;
       this.ehRu = ehRu;
       this.ehRf = ehRf;
       this.xdead = xdead;
    }
   
    public int getCodConstrucao() {
        return this.codConstrucao;
    }
    
    public void setCodConstrucao(int codConstrucao) {
        this.codConstrucao = codConstrucao;
    }
    public Construcao getConstrucao() {
        return this.construcao;
    }
    
    public void setConstrucao(Construcao construcao) {
        this.construcao = construcao;
    }
    public Boolean getEhSt() {
        return this.ehSt;
    }
    
    public void setEhSt(Boolean ehSt) {
        this.ehSt = ehSt;
    }
    public Boolean getEhRu() {
        return this.ehRu;
    }
    
    public void setEhRu(Boolean ehRu) {
        this.ehRu = ehRu;
    }
    public Boolean getEhRf() {
        return this.ehRf;
    }
    
    public void setEhRf(Boolean ehRf) {
        this.ehRf = ehRf;
    }
    public Boolean getXdead() {
        return this.xdead;
    }
    
    public void setXdead(Boolean xdead) {
        this.xdead = xdead;
    }




}


