package cmd.entidade;
// Generated 29/10/2017 11:08:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PessoaJuridica generated by hbm2java
 */
public class PessoaJuridica  implements java.io.Serializable {


     private int codCliente;
     private Cliente cliente;
     private String cnpj;
     private String razaoSocial;
     private String ramoAtuacao;
     private Date dataFundacao;
     private Boolean xdead;

    public PessoaJuridica() {
    }

	
    public PessoaJuridica(Cliente cliente) {
        this.cliente = cliente;
    }
    public PessoaJuridica(Cliente cliente, String cnpj, String razaoSocial, String ramoAtuacao, Date dataFundacao, Boolean xdead) {
       this.cliente = cliente;
       this.cnpj = cnpj;
       this.razaoSocial = razaoSocial;
       this.ramoAtuacao = ramoAtuacao;
       this.dataFundacao = dataFundacao;
       this.xdead = xdead;
    }
   
    public int getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(int codCliente) {
        this.codCliente = codCliente;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getRamoAtuacao() {
        return this.ramoAtuacao;
    }
    
    public void setRamoAtuacao(String ramoAtuacao) {
        this.ramoAtuacao = ramoAtuacao;
    }
    public Date getDataFundacao() {
        return this.dataFundacao;
    }
    
    public void setDataFundacao(Date dataFundacao) {
        this.dataFundacao = dataFundacao;
    }
    public Boolean getXdead() {
        return this.xdead;
    }
    
    public void setXdead(Boolean xdead) {
        this.xdead = xdead;
    }




}


