/*
 * Deixai toda esperança, ó vós que entrais!
 */
package cmd.novo.tela;

import cmd.Validacao.Validar;
import cmd.controle.CadFuncionarioControle;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Tela de registro de funcionários
 * @author Usuario Cadastra novos usuarios
 */
public class TFuncionario extends javax.swing.JInternalFrame {

    /**
     * Controla a quantidade de Janelas abertas
     */
    public static TFuncionario funcionarioT;

    public static TFuncionario getInstancia() {
        if (funcionarioT == null) {
            funcionarioT = new TFuncionario();
        }
        return funcionarioT;
    }

    /**
     * Creates new form FuncionarioT
     */
    public TFuncionario() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nome_func = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bt_cadastro_func = new javax.swing.JButton();
        bt_sair_func = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        txt_senha_confirma = new javax.swing.JPasswordField();
        img_funcionario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bem-Vindo a Área de Cadastro de Funcionarios");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        txt_nome_func.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Senha");

        bt_cadastro_func.setBackground(new java.awt.Color(153, 153, 255));
        bt_cadastro_func.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_cadastro_func.setText("Cadastrar");
        bt_cadastro_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastro_funcActionPerformed(evt);
            }
        });

        bt_sair_func.setBackground(new java.awt.Color(153, 153, 255));
        bt_sair_func.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_sair_func.setText("Sair");
        bt_sair_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sair_funcActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Confirma Senha");

        txt_senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_senha_confirma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        img_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmd/imagens/funcionarios.jpg"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_cadastro_func)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_sair_func))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_senha_confirma, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txt_senha)
                                        .addComponent(txt_nome_func))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(img_funcionario)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nome_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_senha_confirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img_funcionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastro_func)
                    .addComponent(bt_sair_func)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_sair_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sair_funcActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_sair_funcActionPerformed

    private void bt_cadastro_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastro_funcActionPerformed
        if ("".equals(txt_nome_func.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Preecha o Nome");
            return;
        }

        if ("".equals(txt_senha.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Preecha a Senha");
            return;
        }
        if ("".equals(txt_senha_confirma.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Preecha o Confirmar Senha");
            return;
        }

        if (!(new String(txt_senha.getPassword()).equals(new String(txt_senha_confirma.getPassword())))) {

            JOptionPane.showMessageDialog(null, "A senha é diferente");
            txt_senha_confirma.requestFocus();
            txt_senha_confirma.setText("");
            return;
        }
        Validar vali = new Validar();
        if (vali.validarSenha(txt_senha.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Sua senha deve ter entre 6 e 16 caracteres");
            return;
        }

        CadFuncionarioControle cadFunC = new CadFuncionarioControle();

        if (cadFunC.cadastrarFuncionario(txt_nome_func.getText(), txt_senha.getText()) == true) {
            txt_nome_func.setText("");
            txt_senha.setText("");
            txt_senha_confirma.setText("");

        }

    }//GEN-LAST:event_bt_cadastro_funcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_nome_func.setText("");
        txt_senha.setText("");
        txt_senha_confirma.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastro_func;
    private javax.swing.JButton bt_sair_func;
    private javax.swing.JLabel img_funcionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_nome_func;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JPasswordField txt_senha_confirma;
    // End of variables declaration//GEN-END:variables
}
