/*
 * Deixai toda esperança, ó vós que entrais!
 */
package cmd.novo.tela;

import cmd.conexao.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 * Tela de Relatórios
 * @author voce
 */
public class TRelatorio extends javax.swing.JInternalFrame {

    public static TRelatorio relatorioT;

    public static TRelatorio getInstancia() {
        if (relatorioT == null) {
            relatorioT = new TRelatorio();
        }
        return relatorioT;
    }

    /**
     * Creates new form RelatorioT
     */
    public TRelatorio() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        bt_rel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_rel1 = new javax.swing.JButton();
        bt_pessoafisica = new javax.swing.JButton();
        bt_pessoajuridica = new javax.swing.JButton();
        bt_rel4 = new javax.swing.JButton();
        bt_rel5 = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");

        bt_rel1.setBackground(new java.awt.Color(153, 153, 255));
        bt_rel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_rel1.setText("Relatório de Materiais");
        bt_rel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rel1ActionPerformed(evt);
            }
        });

        bt_pessoafisica.setBackground(new java.awt.Color(153, 153, 255));
        bt_pessoafisica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_pessoafisica.setText("Relatório de Pessoa Física");
        bt_pessoafisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pessoafisicaActionPerformed(evt);
            }
        });

        bt_pessoajuridica.setBackground(new java.awt.Color(153, 153, 255));
        bt_pessoajuridica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_pessoajuridica.setText("Relatório de Pessoa Jurídica");
        bt_pessoajuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pessoajuridicaActionPerformed(evt);
            }
        });

        bt_rel4.setBackground(new java.awt.Color(153, 153, 255));
        bt_rel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_rel4.setText("Relatório de Pedidos");
        bt_rel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rel4ActionPerformed(evt);
            }
        });

        bt_rel5.setBackground(new java.awt.Color(153, 153, 255));
        bt_rel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_rel5.setText("Relatório de Endereços");
        bt_rel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rel5ActionPerformed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(153, 153, 255));
        btn_sair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bem-Vindo a Área de Relatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_pessoafisica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(bt_rel1))
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bt_pessoajuridica))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(bt_rel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(bt_rel5)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btn_sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_rel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_pessoafisica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_pessoajuridica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_rel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_rel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_rel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rel1ActionPerformed
        Connection con = ConnectionFactory.getConexao();
        PreparedStatement stat = null;
        ResultSet rs = null;

        try {
            stat = con.prepareStatement("SELECT * from material");
            rs = stat.executeQuery();
            JRResultSetDataSource relatresult = new JRResultSetDataSource(rs);
            JasperPrint print = JasperFillManager.fillReport("src\\cmd\\Relatorios\\Materiais.jasper", new HashMap(), relatresult);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
            view.toFront();
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar o relatorio: \n" + e);
        } catch (SQLException ex) {
            Logger.getLogger(TRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ConnectionFactory.fechaConexão(con, stat);
        }
    }//GEN-LAST:event_bt_rel1ActionPerformed

    private void bt_pessoafisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pessoafisicaActionPerformed
        Connection con = ConnectionFactory.getConexao();
        PreparedStatement stat = null;
        ResultSet rs = null;

        try {
            stat = con.prepareStatement("SELECT c.CodCliente, pf.Nome, t.Numero, c.Email \n"
                    + "FROM Cliente AS c\n"
                    + "INNER JOIN PessoaFisica AS pf on pf.CodCliente = c.CodCliente\n"
                    + "INNER JOIN Telefone AS t on t.CodCliente = c.CodCliente\n"
                    + "ORDER BY pf.Nome");
            rs = stat.executeQuery();
            JRResultSetDataSource relatresult = new JRResultSetDataSource(rs);
            JasperPrint print = JasperFillManager.fillReport("src\\cmd\\Relatorios\\PessoasFisicas.jasper", new HashMap(), relatresult);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
            view.toFront();
        } catch (SQLException ex) {
            Logger.getLogger(TRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException e) {
            System.out.println("_ERRO: " + e);
            Logger.getLogger(TRelatorio.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            ConnectionFactory.fechaConexão(con, stat);
        }
    }//GEN-LAST:event_bt_pessoafisicaActionPerformed

    private void bt_pessoajuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pessoajuridicaActionPerformed
        Connection con = ConnectionFactory.getConexao();
        PreparedStatement stat = null;
        ResultSet rs = null;

        try {
            stat = con.prepareStatement("SELECT c.CodCliente, pj.NomeReferencia, t.Numero, c.Email\n"
                    + "FROM Cliente AS c\n"
                    + "INNER JOIN PessoaJuridica AS pj ON pj.CodCliente = c.CodCliente\n"
                    + "INNER JOIN Telefone AS t ON t.CodCliente = c.CodCliente\n"
                    + "ORDER BY pj.NomeReferencia");
            rs = stat.executeQuery();
            JRResultSetDataSource relatresult = new JRResultSetDataSource(rs);
            JasperPrint print = JasperFillManager.fillReport("src\\cmd\\Relatorios\\PessoasJuridicas.jasper", new HashMap(), relatresult);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
            view.toFront();
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar o relatorio: \n" + e);
        } catch (SQLException ex) {
            Logger.getLogger(TRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ConnectionFactory.fechaConexão(con, stat);
        }
    }//GEN-LAST:event_bt_pessoajuridicaActionPerformed

    private void bt_rel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rel4ActionPerformed
        Connection con = ConnectionFactory.getConexao();
        PreparedStatement stat = null;
        ResultSet rs = null;

        try {
            stat = con.prepareStatement("SELECT * from pedido_orcamento");
            rs = stat.executeQuery();
            JRResultSetDataSource relatresult = new JRResultSetDataSource(rs);
            JasperPrint print = JasperFillManager.fillReport("src\\cmd\\Relatorios\\Pedidos_orc.jasper", new HashMap(), relatresult);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
            view.toFront();
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar o relatorio: \n" + e);
        } catch (SQLException ex) {
            Logger.getLogger(TRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ConnectionFactory.fechaConexão(con, stat);
        }
    }//GEN-LAST:event_bt_rel4ActionPerformed

    private void bt_rel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rel5ActionPerformed

    }//GEN-LAST:event_bt_rel5ActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_pessoafisica;
    private javax.swing.JButton bt_pessoajuridica;
    private javax.swing.JButton bt_rel1;
    private javax.swing.JButton bt_rel4;
    private javax.swing.JButton bt_rel5;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
